# Generated by Django 3.2.6 on 2021-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
