# Generated by Django 3.2.6 on 2021-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='url',
            field=models.URLField(default='index.html'),
        ),
    ]
